Omicron_Batch/sparsh803.txt

sparsh803 completed Task-1

---

Omicron_Batch/IIT-252-Himanshu-Shekhar.txt

Himanshu276330 completed Task-1

Creating a text file and Answering the question

---

Omicron_Batch/riddhikedia.txt

 riddhikedia completed TASK 1

---

Omicron_Batch/Tan-Code-may.txt

I enjoyed using git and GitHub and thank you seniors for teaching it so well.

Tan-Code-may information updated

---

Omicron_Batch/tsunami03.txt

Finished Task-1 of FOSS Workshop 2022

tsunami03 completed Task-1

---

Omicron_Batch/yashg-116.txt

Hello seniors, myself Yash Gupta (IEC2021064). I have completed task-1. Thanks.

yashg-116 completed Task-1

---

Omicron_Batch/PiyushGG18.txt

<PiyushGG18>completed task-1

---

Omicron_Batch/vipuljain100.txt

This is my Task 1 
Thank You Seniors

vipuljain100

---

Omicron_Batch/amishas1125.txt

Amisha Singh IIT2021050
GitHub username: amishas1125

amishas1125 completed Task-1

---

Omicron_Batch/Aneesh.txt

done with questionsgit add -A!

---

Omicron_Batch/rajat397.txt

Rajat Srivastava (github id - rajat397) has copmpleted task 1

rajat397 completed Task-1

---

Omicron_Batch/mehakgupta1103.txt

This is my first task in Git. It was an awesome beginning.

mehakgupta1103

---

Omicron_Batch/DhruvHeisenberg.txt

I learned a lot while doing the task.

FOSS TASK 1 COMPLETED 

---

Omicron_Batch/t-a-n-m-a-y.txt

t-a-n-m-a-y

---

Omicron_Batch/AdityaSharma.txt

Task 1 done

---

Omicron_Batch/Cromyl.txt

Adding the txt file as per task 1 of the APK Month

Kaushik Mullick has made the change

---

Omicron_Batch/Naman-Pundir.txt

Naman-Pundir

---

Omicron_Batch/ja1n-aman.txt

ja1n-aman Completedtask1

---

Omicron_Batch/aditya3773.txt

Thankyou...Enjoyed it and Excited

aditya3773 Completed Task-1

---

Omicron_Batch/sgishere.txt

sgishere  completed Task

---

Omicron_Batch/Upasana112.txt

Upasana112 completed Task 1

---

Omicron_Batch/saxenaakshay15.txt

Akshay completed Task

---

Omicron_Batch/RayLikesAnime.txt

biodata kinda

---

Omicron_Batch/DeepaKumarVerma.txt

<DeepaKumarVerma> Completed task 1

saved DeepaKumarVerma.txt

---

Omicron_Batch/ArjavK.txt

Reverts GeekHaven/FOSS-APK-Month#205

Revert "DeadliestDemon Completed-Task 1"

---

Omicron_Batch/Saransh-Yadav.txt

SaranshYadav created a pull request for Task-1

SaranshYadav completed Task-1

---

Omicron_Batch/Abhijanitha.txt

Abhijanitha

---

Omicron_Batch/Ram5anthosh.txt

Ram5anthosh.txt completed task 1

---

Omicron_Batch/jishwithareddy.txt

jishwithareddy completed Task-1

jishwithareddy completed Task-1

---

Omicron_Batch/praneeth8555.txt

praneeth8555

---

Omicron_Batch/SakshamGolechha.txt

SakshamGolechha

---

Omicron_Batch/vikasbommakanti.txt

vikasbommakanti

---

Omicron_Batch/YASIR123ARAFAT.txt

My changes

---

Omicron_Batch/vishnu prasanth

is it right this time at least

Create vishnu prasanth

---

Omicron_Batch/SujithaNuli.txt

SujithaNuli

---

Omicron_Batch/Kjniharika.txt

Kjniharika

---

Omicron_Batch/Anshul Bhardwaj IT 57.txt

@seniors this is my entry for 1st task . please consider it.

anshul bhardwaj 1st task

---

Omicron_Batch/sushantk1274.txt

I have successfully completed the Task-1

sushantk1274 completed task 1

---

Omicron_Batch/anandcodes2805.txt

Sir I have completed the task assigned .

A sample file

---

Omicron_Batch/Sumit.txt

New File added

---

Omicron_Batch/farhanhaider624.txt

farhanhaider624 completed Task1

---

Omicron_Batch/NitishKushwaha.txt

NitishKushwaha completed Task-1

NitishKushwaha completed Task-1

---

Omicron_Batch/deepak039.txt

deepak039 completed task 1
